dist: bionic

services:
  - couchdb

language: node_js

before_script:
  - until ruby -rsocket -e "TCPSocket.new('localhost',5984)"; do sleep 1; done
  - curl localhost:5984/
  - curl localhost:5984/_membership
  - curl -X PUT localhost:5984/_node/_local/_config/couch_peruser/enable -d "\"true\""
  - curl -X PUT localhost:5984/_node/_local/_config/couch_peruser/delete_dbs -d "\"true\""
  - curl localhost:5984/_node/_local/_config/couch_peruser

node_js:
  - "13"
